### List Todos
GET http://localhost:3000/api/todos

### Create Todo
POST http://localhost:3000/api/todos
Content-Type: application/json

{
	"title": "TODO 1",
	"description": "This is the first todo item"
}

### Update Todo
PUT http://localhost:3000/api/todos/2
Content-Type: application/json

{
	"completed": true
}

### Delete Todo
DELETE http://localhost:3000/api/todos/1

### Get Todo
GET http://localhost:3000/api/todos/2
